### ISSUE TITLE
Wheels haven't been published for 2.0.0

### ISSUE THREAD

**Issue by JohnGedik** [geventhttpclient/geventhttpclient#163] opened 2022-07-27 18:33 UTC
Is it intentional that wheels haven't been published for 2.0.0? Our locust Jenkins builds are failing because of dependency.

**Comment by cyberw** [comment] 2022-07-27 21:29
no, its not intentional, but github is deprecating macOS-10.15, which made the build fail half way through. Will try again once their "brownout" is finished. https://github.com/geventhttpclient/geventhttpclient/actions/runs/2746356919

**Comment by cyberw** [comment] 2022-07-27 21:33
`--prefer-binary` may be an appropriate option for you https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-prefer-binary

**Comment by JohnGedik** [comment] 2022-07-27 21:42
Thanks

**Comment by cyberw** [comment] 2022-07-27 22:40
Does it work for you now?

**Comment by alicederyn** [comment] 2022-07-28 07:00
Our reproducer seems to be fixed now, thanks!

**Closed** 2022-07-28 07:30 UTC
