### ISSUE TITLE
get_default_verify_paths() not used

### ISSUE THREAD

**Issue by laurentL** [geventhttpclient/geventhttpclient#124] opened 2020-03-31 12:28 UTC
```python            
            try:
                from ssl import get_default_verify_paths
            except ImportError:
                _CA_CERTS = None
            else:
                _certs = get_default_verify_paths()
                _CA_CERTS = _certs.cafile or _certs.capath

            if not _CA_CERTS or os.path.isdir(_CA_CERTS):
                import certifi
                _CA_CERTS = certifi.where()
```

 _certs.capath is populate =>
    os.path.isdir(_CA_CERTS) == True
  _CA_CERTS is overide by certifi, but not contain all system root certificate

in conclusion, certificates such as the one from google are no longer accepted.

it seems to me that the line must have been:
```python
            if not _CA_CERTS or not os.path.isdir(_CA_CERTS):
```

**Comment by ml31415** [comment] 2024-04-11 12:13
I had experimented with it a bit. Just changing this one line clearly doesn't cut it as it raises a bunch of other issues. Can you provide more details for the environment in which it fails for you?

**Comment by ml31415** [comment] 2024-04-15 12:56
@laurentL I suppose this might have been related to some older version of python or gevent? As I can't reproduce the issue, I'm closing it right now. If it's still up to date, let me know and we can reopen it.

**Closed by ml31415** 2024-04-15 12:56 UTC
